

 


URL: https://naveenautomationlabs.com/opencart/
url: 

Username:Tiwaridharam720@gmail.com
Password:Dms@gemtest1

browser:chrome



fname: Dharam		
lName: Tiwari
email: tiwaridharam720@gmail.com
telephone: 9354984729
password: Dms@Test1
confirmpassword: Dms@Test1

